version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - rm -rf target  # Clean the target directory
      - mvn clean install -U
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - target/chat-bot.jar
  discard-paths: yes



