version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install -U
      - mvn clean package -e
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - target/chat-bot.jar
  discard-paths: yes
